<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <IsPackable>false</IsPackable>
        <NeutralLanguage>en</NeutralLanguage>
        <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <CopyDocumentationFileToOutputDirectory>false</CopyDocumentationFileToOutputDirectory>
        <PublishDocumentationFiles>false</PublishDocumentationFiles>
        <PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>

        <AssemblyVersion>1.2.0</AssemblyVersion>
        <FileVersion>1.2.0</FileVersion>
        <Company>PureLogicCode.com</Company>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="CHDMounter" />
        <InternalsVisibleTo Include="CHDMounter_WinFsp" />
        <InternalsVisibleTo Include="CHDMounter.Core.Tests" />
        <InternalsVisibleTo Include="CHDMounter_Tester" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Images\logo.png" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Meziantou.Analyzer" Version="3.0.193">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <ProjectReference Include="..\VideoGameFileSystemParser\VideoGameFileSystemParser.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="WPF-UI" Version="4.3.0" />
    </ItemGroup>

</Project>
