<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <AssemblyVersion>1.2.0</AssemblyVersion>
        <FileVersion>1.2.0</FileVersion>
        <NeutralLanguage>en</NeutralLanguage>
        <Company>PureLogicCode.com</Company>
        <RootNamespace>Tester</RootNamespace>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <CopyDocumentationFileToOutputDirectory>false</CopyDocumentationFileToOutputDirectory>
        <PublishDocumentationFiles>false</PublishDocumentationFiles>
        <PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>

        <ApplicationIcon>Icon\chd.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CHDMounter.Core\CHDMounter.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Meziantou.Analyzer" Version="3.0.193">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="WPF-UI" Version="4.3.0" />
        <PackageReference Include="QuestPDF" Version="2026.8.0" />
    </ItemGroup>

</Project>
